defaultContentLanguage = 'en'
baseURL = 'https://FilippoGurioli.github.io/curriculum-vitae/'
title = 'My Curriculum Vitae'

[languages]
  [languages.en]
    languageName = 'English'
    weight = 1
    contentDir = 'content/en'
  [languages.it]
    languageName = 'Italiano'
    weight = 2
    contentDir = 'content/it'
