name: Deploy Hugo to GHP and LaTeX to GH releases
on:
  push:
    branches: [ main ]

permissions:
  contents: write
  pages: write
  id-token: write

jobs:
  build-web:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      
      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v3
        with:
          hugo-version: 'latest'

      - name: Build
        run: hugo --minify

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./public

  deploy-web:
    needs: build-web
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4

  build-pdf:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: pip install Jinja2 PyYAML

      - name: Generate TeX from YAML
        run: python generate_latex_cv.py

      - name: Compile LaTeX to PDF
        uses: xu-cheng/latex-action@v3
        with:
          root_file: cv.tex

      - name: Upload PDF Artifact
        uses: actions/upload-artifact@v4
        with:
          name: CV-PDF
          path: cv.pdf

      - name: Generate Tag
        id: tagger
        run: |
          TAG_NAME="v$(date +'%Y.%m.%d-%H%M')"
          echo "tag=$TAG_NAME" >> $GITHUB_OUTPUT
          git tag $TAG_NAME
          git push origin $TAG_NAME
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Set Tag Name
        id: vars
        run: echo "tag=v$(date +'%Y.%m.%d-%H%M')" >> $GITHUB_OUTPUT

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ steps.vars.outputs.tag }}
          name: "CV Release ${{ steps.vars.outputs.tag }}"
          files: cv.pdf
          body: "Automated CV build."
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
